// 本地论证库：按“问题 × 流派”组织，而不是按某一对流派配置页面。
// 引擎通过 respondTags 与上一轮主张的 tags 动态匹配反驳。
export const debateStances = {
  human: {
    'ancient-greece': {
      label: '理性—德性的人',
      posture: '人具有自然目的，并通过习惯实现德性。',
      opening: {
        title: '人是有德性潜能的理性动物',
        body: '人不是偶然欲望的集合；灵魂中的理性秩序使人能够在共同体与实践中实现善。',
        tags: ['essence', 'virtue', 'reason'],
      },
      responses: [
        {
          title: '没有目的的自由会失去方向',
          body: '即使人没有现成本质，选择仍然要回答“什么值得选择”；否则自由就会退化为任意。',
          respondTags: ['freedom', 'existence', 'choice'],
          tags: ['essence', 'virtue'],
          strength: 8,
        },
        {
          title: '先理解人的功能，再谈人的例外',
          body: '无论个体怎样选择，他都处在生命、关系与实践之中；这些结构提供了批判生活的尺度。',
          respondTags: ['experience', 'self', 'recognition', 'history'],
          tags: ['nature', 'practice'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '完成本性，而不是不断逃离本性',
        body: '人的问题不是发明一个空洞的自我，而是在稳定实践中让理性与德性成形。',
        tags: ['flourishing', 'virtue'],
      },
    },
    modern: {
      label: '自我修正的主体',
      posture: '人以理性和经验不断修正传统与偏见。',
      opening: {
        title: '人是能够怀疑并重建判断的主体',
        body: '我可以怀疑传统、感官与欲望，但正在进行的思维提供了一个可以重新出发的支点。',
        tags: ['reason', 'self', 'doubt'],
      },
      responses: [
        {
          title: '目的本身也必须接受怀疑',
          body: '被称作“本性”的东西可能只是未经检验的习俗；真正可靠的是人修正前提的能力。',
          respondTags: ['essence', 'virtue', 'order', 'form'],
          tags: ['reason', 'doubt'],
          strength: 8,
        },
        {
          title: '从抽象本质回到可检验的经验',
          body: '关于人的任何断言，都必须说明它在行为、情感与认知经验中如何得到验证。',
          respondTags: ['existence', 'freedom', 'recognition', 'spirit'],
          tags: ['experience', 'evidence'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '人的尊严在于自我修正',
        body: '人不必然是现成本质，也不只是处境的产物，而能通过方法与制度减少幻觉。',
        tags: ['progress', 'reason'],
      },
    },
    'german-idealism': {
      label: '历史中的自我意识',
      posture: '人在劳动、制度与他人承认中生成。',
      opening: {
        title: '人是在历史中生成的自我意识',
        body: '孤立个人只是抽象；人通过劳动、制度与他人承认，才把自己理解为自由的存在。',
        tags: ['self-consciousness', 'recognition', 'history', 'freedom'],
      },
      responses: [
        {
          title: '经验中的人已经预设了主体结构',
          body: '感觉材料不会自行成为经验；统觉、范畴与意义关系先使经验成为可理解的整体。',
          respondTags: ['experience', 'evidence', 'doubt', 'causation'],
          tags: ['categories', 'self-consciousness'],
          strength: 9,
        },
        {
          title: '个人始终处在伦理生活中',
          body: '选择、欲望与理性都在家庭、社会和国家的历史关系里获得具体内容。',
          respondTags: ['existence', 'choice', 'nature', 'virtue'],
          tags: ['ethical-life', 'recognition'],
          strength: 7,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '自由在历史中实现',
        body: '人的完成不是退回内心，而是在制度与共同生活中使自由成为客观现实。',
        tags: ['history', 'freedom', 'ethical-life'],
      },
    },
    existentialism: {
      label: '被判定为自由的存在',
      posture: '存在先于本质，选择定义人。',
      opening: {
        title: '人首先存在，然后把自己造成什么',
        body: '没有神圣剧本或固定本性等待发现；人在具体处境中选择，并对自己成为的形象负责。',
        tags: ['existence', 'freedom', 'choice', 'responsibility'],
      },
      responses: [
        {
          title: '“本性”不能替我承担选择',
          body: '即使你描述出人类的普遍功能，我仍然必须决定是否承认这种生活是我的生活。',
          respondTags: ['essence', 'virtue', 'form', 'order', 'nature'],
          tags: ['choice', 'responsibility'],
          strength: 9,
        },
        {
          title: '处境中的自由无法被体系吸收',
          body: '历史与社会可以塑造材料，却不能取消“我如何回应处境”这一无法替代的决定。',
          respondTags: ['self-consciousness', 'recognition', 'experience', 'self'],
          tags: ['existence', 'situation'],
          strength: 7,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '成为人，就是持续承担自由',
        body: '答案不在概念深处，而在每一个具体选择及其所承担的责任之中。',
        tags: ['responsibility', 'choice'],
      },
    },
  },

  knowledge: {
    'ancient-greece': {
      label: '回忆与理念秩序',
      posture: '知识是对普遍、恒真秩序的理性把握。',
      opening: {
        title: '知识是灵魂对恒真秩序的回忆',
        body: '可变意见来自感觉，真正的知识则朝向数学、德性与存在本身的普遍形式。',
        tags: ['truth', 'reason', 'forms'],
      },
      responses: [
        {
          title: '特殊经验不能证明普遍必然性',
          body: '再多感觉案例也只说明“曾经如此”；必然真理要求理性对形式的把握。',
          respondTags: ['experience', 'evidence', 'causation', 'phenomena'],
          tags: ['reason', 'forms', 'truth'],
          strength: 9,
        },
        {
          title: '讨论知识不能脱离“存在什么”',
          body: '如果真理只是主体内部的表象，我们甚至无法说明错误判断如何可能。',
          respondTags: ['perspective', 'practice', 'limits', 'appearance'],
          tags: ['being', 'truth'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '知识的终点是可理解的秩序',
        body: '可靠知识不在于堆积印象，而在于让理性穿越变化，抵达定义与形式。',
        tags: ['forms', 'reason', 'truth'],
      },
    },
    modern: {
      label: '经验与概率',
      posture: '知识始于经验，并必须持续接受检验。',
      opening: {
        title: '知识是被经验校正的可靠推断',
        body: '除观念关系外，所有事实推理都依赖过去经验；证据越强，信念越应保持概率性。',
        tags: ['experience', 'evidence', 'doubt', 'probability'],
      },
      responses: [
        {
          title: '必然性常是习惯投到世界上的影子',
          body: '我们看到先后相继，却看不见必然力量；理性若离开经验，容易把习惯误当真理。',
          respondTags: ['forms', 'reason', 'categories', 'concept', 'spirit'],
          tags: ['causation', 'experience', 'doubt'],
          strength: 8,
        },
        {
          title: '观念可以清楚，事实仍需验证',
          body: '可设想性与定义不能告诉我们外部世界实际怎样；必须回到观察和可重复证据。',
          respondTags: ['truth', 'being', 'perspective', 'practice'],
          tags: ['evidence', 'experience'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '最好的知识保持可修正',
        body: '绝对确定性是过高的要求；经验探究以证据、概率与持续怀疑替代独断。',
        tags: ['evidence', 'probability'],
      },
    },
    'german-idealism': {
      label: '先验条件',
      posture: '知识研究使有序经验得以可能的条件。',
      opening: {
        title: '对象在主体的先天条件中显现',
        body: '感性形式与知性范畴并非从经验中借来，它们使有序经验和客观判断成为可能。',
        tags: ['categories', 'limits', 'reason', 'appearance'],
      },
      responses: [
        {
          title: '经验不能证明使经验可能的条件',
          body: '如果因果性只是习惯，就无法说明客观经验为何能具有普遍有效的秩序。',
          respondTags: ['experience', 'evidence', 'causation', 'probability'],
          tags: ['categories', 'reason', 'limits'],
          strength: 9,
        },
        {
          title: '越过边界的理念没有客观对象',
          body: '理性可以设想灵魂、整体与绝对，但一旦把它们当作经验对象，就会产生幻相。',
          respondTags: ['forms', 'being', 'truth'],
          tags: ['limits', 'critique'],
          strength: 8,
        },
        {
          title: '任何视角都已经包含判断结构',
          body: '无论知识来自行动还是解释，若没有时空、因果与自我意识的统一，就没有可传达的经验。',
          respondTags: ['perspective', 'practice', 'existence'],
          tags: ['categories', 'limits'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '批判划界，也是为自由留出地盘',
        body: '知识不能穷尽世界，但它能澄清自身的条件与界限，避免理性越界。',
        tags: ['limits', 'critique'],
      },
    },
    existentialism: {
      label: '处境中的理解',
      posture: '知识首先是此在在世界中存在的方式。',
      opening: {
        title: '知识不是旁观，而是此在对世界的筹划',
        body: '我们并非先有中立表象再去认识世界；理解总已带着关切、实践和“我能如何存在”。',
        tags: ['existence', 'practice', 'perspective'],
      },
      // 故意只提供一张强匹配回应：某些组合下它会提前进入“无更合适反驳”的非理想流程。
      responses: [
        {
          title: '方法论的客观主义遗忘了存在者',
          body: '把一切对象化之后，那个提问、担忧并在世界中理解的存在者反而消失了。',
          respondTags: ['categories', 'evidence', 'forms', 'probability', 'reason'],
          tags: ['being', 'existence', 'practice'],
          strength: 8,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '理解总回到我的能在',
        body: '知识不是收集中立事实，而是揭示世界，并反过来规定我将成为谁。',
        tags: ['existence', 'responsibility'],
      },
    },
  },

  real: {
    'ancient-greece': {
      label: '形式与实体',
      posture: '真实是形式与质料构成的可理解整体。',
      opening: {
        title: '真实不只是流变现象，而是可定义的实体',
        body: '感觉展示许多样子，但理智在其中把握形式，才使事物作为自身被理解。',
        tags: ['form', 'substance', 'order'],
      },
      responses: [
        {
          title: '现象要求一个显现者',
          body: '如果只有表象与感觉，就无法说明为何不同现象能够属于同一个稳定事物。',
          respondTags: ['phenomena', 'experience', 'appearance', 'causation'],
          tags: ['substance', 'form'],
          strength: 9,
        },
        {
          title: '语言中的意义仍指向可理解结构',
          body: '语言可以开启世界，但意义不是任意漂浮的；它依赖事物之间可被理性辨别的秩序。',
          respondTags: ['being', 'world', 'language', 'concept', 'spirit'],
          tags: ['form', 'order'],
          strength: 8,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '真实是秩序，不只是显现',
        body: '哲学要从变化的外观回到实体、形式与目的所构成的可理解整体。',
        tags: ['form', 'substance'],
      },
    },
    modern: {
      label: '可测量的现象',
      posture: '真实必须在经验与数学关系中接受审查。',
      opening: {
        title: '真实是可被经验追踪的现象关系',
        body: '形而上学实体若不能产生可观察差别，就应被怀疑；可靠知识停在证据支持的关系内。',
        tags: ['phenomena', 'experience', 'causation'],
      },
      responses: [
        {
          title: '不可观察的实体容易成为词语虚构',
          body: '当本质与绝对精神无法被经验检验时，它们可能只是我们给神秘感起的名字。',
          respondTags: ['form', 'substance', 'order', 'spirit', 'concept'],
          tags: ['experience', 'evidence'],
          strength: 8,
        },
        {
          title: '承认真实，而不假装穷尽真实',
          body: '经验边界之外或许仍有东西，但那不是知识能够有意义地断言的对象。',
          respondTags: ['being', 'world', 'language', 'appearance'],
          tags: ['limits', 'phenomena'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '清醒地停在证据边界内',
        body: '真实不是被推理出来的宏大整体，而是在观察、数学与实验中接受检验的关系。',
        tags: ['evidence', 'phenomena'],
      },
    },
    'german-idealism': {
      label: '精神的自我展开',
      posture: '真实是精神在历史中显现的整体。',
      opening: {
        title: '真实即精神在历史中的自我展开',
        body: '孤立的物与抽象主体都不完整；概念在矛盾、扬弃与历史制度中把自己实现为整体。',
        tags: ['spirit', 'concept', 'history', 'appearance'],
      },
      responses: [
        {
          title: '未经概念把握的现象不是整体',
          body: '经验只给出并列事实，无法说明它们为何能在一个自我展开的意义整体中统一。',
          respondTags: ['phenomena', 'experience', 'causation', 'evidence', 'limits'],
          tags: ['concept', 'spirit'],
          strength: 9,
        },
        {
          title: '静止形式无法容纳矛盾与历史',
          body: '真实不是摆在眼前的实体，而是通过否定自身并重新统一而生成的过程。',
          respondTags: ['form', 'substance', 'order'],
          tags: ['dialectic', 'history'],
          strength: 8,
        },
        {
          title: '把真实当作外在对象，已经是一种抽象',
          body: '主客二分本身只是精神展开的环节；停在二分里，就无法理解真理为何是整体。',
          respondTags: ['being', 'world', 'language'],
          tags: ['concept', 'spirit'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '真理是整体，也是过程',
        body: '真实不在某个孤立基底背后，而在概念扬弃矛盾并实现自由的历史运动中。',
        tags: ['spirit', 'history', 'dialectic'],
      },
    },
    existentialism: {
      label: '存在的开显',
      posture: '真实通过在世存在、实践与语言开显。',
      opening: {
        title: '真实首先不是物，而是存在者在世界中的开显',
        body: '人不是封闭主体，而是已经在世界中；事物在实践、情绪与语言的境域里显现为有意义的。',
        tags: ['being', 'world', 'language', 'appearance'],
      },
      responses: [
        {
          title: '对象化思维遮蔽了存在问题',
          body: '把真实还原为实体或因果对象，恰恰遗忘了使对象能够显现的开放世界。',
          respondTags: ['form', 'substance', 'phenomena', 'causation', 'evidence'],
          tags: ['being', 'world'],
          strength: 9,
        },
        {
          title: '存在不能被绝对体系吸收',
          body: '体系可以安排概念，却无法把提问者的有限性、时间性和被抛境况完全推导出来。',
          respondTags: ['concept', 'spirit', 'categories', 'reason'],
          tags: ['finitude', 'being'],
          strength: 8,
        },
        {
          title: '世界不是现成容器，而是意义境域',
          body: '在我们判断真假之前，已经身处一个因关切、工具和语言而展开的世界。',
          respondTags: ['experience', 'limits', 'appearance'],
          tags: ['world', 'being'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '向存在本身保持开放',
        body: '不要把存在者当成唯一答案；真正的思想要回到使开显得以发生的境域。',
        tags: ['being', 'language'],
      },
    },
  },

  life: {
    'ancient-greece': {
      label: '德性与幸福',
      posture: '好生活是合德性的现实活动。',
      opening: {
        title: '好生活是灵魂合乎德性的实现',
        body: '幸福不是短暂感受，而是在共同体、习惯与实践智慧中持续完成的善好生活。',
        tags: ['virtue', 'habit', 'flourishing'],
      },
      responses: [
        {
          title: '欲望需要被实践理性安排',
          body: '顺着激情与计算生活，可能得到许多手段，却不知道哪一种生活真正值得过。',
          respondTags: ['passion', 'interest', 'progress'],
          tags: ['virtue', 'practical-reason'],
          strength: 8,
        },
        {
          title: '选择若没有德性，只会加重混乱',
          body: '自由本身不保证善好；它需要习惯、友谊与正义把选择塑造成稳定生活。',
          respondTags: ['choice', 'absurdity', 'responsibility', 'freedom', 'ethical-life'],
          tags: ['virtue', 'community'],
          strength: 8,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '好生活靠习惯，不靠一次顿悟',
        body: '人在反复做公正、节制而勇敢的事中，成为公正、节制而勇敢的人。',
        tags: ['virtue', 'habit', 'flourishing'],
      },
    },
    modern: {
      label: '激情、利益与制度',
      posture: '理性引导激情，并通过制度改善生活条件。',
      opening: {
        title: '好生活从理解人类激情开始',
        body: '理性不凭空创造目的，它帮助激情避免相互毁灭，并通过制度把利益转化为稳定合作。',
        tags: ['passion', 'interest', 'progress'],
      },
      responses: [
        {
          title: '德性话语也可能掩盖激情与利益',
          body: '若不考察欲望、权力和制度条件，道德习惯很容易把既有秩序误认为自然善好。',
          respondTags: ['virtue', 'habit', 'flourishing', 'form', 'order'],
          tags: ['interest', 'critique'],
          strength: 8,
        },
        {
          title: '仅凭选择无法改变造成苦难的条件',
          body: '英雄式的个人决断若缺少知识与制度，就无法持续减少痛苦、扩大安全与合作。',
          respondTags: ['absurdity', 'choice', 'responsibility', 'freedom'],
          tags: ['progress', 'institution'],
          strength: 8,
        },
        {
          title: '改善生活，先降低支配生活的幻觉',
          body: '理性的谦逊能识别激情的诡计，也能通过可检验的制度安排改善日常条件。',
          respondTags: ['ethical-life', 'history', 'authenticity', 'meaning'],
          tags: ['reason', 'progress'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '驯化激情，并改善生活条件',
        body: '不要求消灭欲望，而是以方法、权利和合作让欲望不再以恐惧统治人。',
        tags: ['institution', 'progress'],
      },
    },
    'german-idealism': {
      label: '自由与伦理生活',
      posture: '好生活是自由在共同历史制度中的实现。',
      opening: {
        title: '好生活是自由在伦理生活中的实现',
        body: '主观选择必须进入财产、法律、家庭与国家等客观制度，自由才不只是任意。',
        tags: ['freedom', 'ethical-life', 'history'],
      },
      responses: [
        {
          title: '私人德性不能提供客观自由',
          body: '善良意愿与习惯若没有法权和制度支撑，就会依赖偶然环境，无法普遍实现。',
          respondTags: ['virtue', 'habit', 'passion', 'interest', 'flourishing'],
          tags: ['ethical-life', 'law'],
          strength: 8,
        },
        {
          title: '没有制度的选择只是形式自由',
          body: '我可以任意选择，但若无相互承认的法律与伦理关系，这种选择就缺少现实内容。',
          respondTags: ['choice', 'absurdity', 'responsibility', 'existence'],
          tags: ['freedom', 'recognition'],
          strength: 9,
        },
        {
          title: '历史让善好生活超出个人内心',
          body: '任何生活理想都在特定伦理整体中获得内容，也必须在历史中接受检验。',
          respondTags: ['authenticity', 'meaning', 'practical-reason'],
          tags: ['history', 'ethical-life'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '在被承认的制度中过自由生活',
        body: '真正的好生活既不是私人德行，也不是任意选择，而是自由成为共同现实。',
        tags: ['ethical-life', 'freedom'],
      },
    },
    existentialism: {
      label: '荒诞与本真性',
      posture: '好生活是在荒诞中本真地承担选择。',
      opening: {
        title: '好生活始于不逃避荒诞',
        body: '世界不预先保证意义；正因如此，人必须以清醒、反抗和承诺创造值得承担的生活。',
        tags: ['absurdity', 'choice', 'responsibility'],
      },
      responses: [
        {
          title: '安稳的习惯可能是对自由的逃避',
          body: '把角色与德性当作第二天性，也许只是躲入众人意见，回避我必须自己选择的焦虑。',
          respondTags: ['virtue', 'flourishing', 'habit', 'order'],
          tags: ['authenticity', 'choice'],
          strength: 9,
        },
        {
          title: '改善条件不能回答为何生活',
          body: '制度与福利可以减少阻碍，却不能替个人决定什么使生命值得活。',
          respondTags: ['passion', 'interest', 'progress', 'institution'],
          tags: ['absurdity', 'meaning'],
          strength: 8,
        },
        {
          title: '没有外在保证，承诺才属于我自己',
          body: '理性、历史或德性可以提供材料，但意义必须在具体处境中被我承担。',
          respondTags: ['freedom', 'ethical-life', 'history', 'practical-reason'],
          tags: ['responsibility', 'authenticity'],
          strength: 6,
          fallback: true,
        },
        {
          title: '保持问题开放',
          body: '即便这一反驳不能完全击倒对方，也迫使对方澄清关键概念的意义、范围与生活后果。',
          respondTags: ['*'],
          tags: ['dialogue'],
          strength: 3,
          fallback: true,
        },
      ],
      closing: {
        title: '清醒地反抗，并真诚地承诺',
        body: '好生活不是获得最终答案，而是在没有终极保证的世界中继续创造意义。',
        tags: ['authenticity', 'responsibility'],
      },
    },
  },
};
